package telas;

import Classes.Cliente;
import Classes.Horário;
import auxHorario.CriarHorario;
import controller.controllerAgendamento;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 0063497
 */
public class segundatelaPanel extends javax.swing.JPanel {

    private primeiratela framepai;
    private Cliente clienteAtual;
    private controller.controllerAgendamento controller;

    /**
     * Creates new form segundatelaPanel
     */
    // DERIVANDO DA PRIMEIRA TELA, VAMOS PEGAR OS DADOS QUE O CLIENTE INFORMOU AO REALIZAR O LOGIN PARA QUE POSSAMOS INFORMAR QUAL O NOME DO CLIENTE ATUAL.
    public segundatelaPanel(primeiratela framepai, Cliente clienteAtual) {
        initComponents();
        this.framepai = framepai;
        this.clienteAtual = clienteAtual;
        this.NomeUsuario.setText(clienteAtual.getNome());
        this.controller = new controllerAgendamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        profissional1 = new javax.swing.JToggleButton();
        profissional2 = new javax.swing.JToggleButton();
        profissional3 = new javax.swing.JToggleButton();
        profissional4 = new javax.swing.JToggleButton();
        horario1 = new javax.swing.JToggleButton();
        horario3 = new javax.swing.JToggleButton();
        horario2 = new javax.swing.JToggleButton();
        horario4 = new javax.swing.JToggleButton();
        horario5 = new javax.swing.JToggleButton();
        horario6 = new javax.swing.JToggleButton();
        horario7 = new javax.swing.JToggleButton();
        servico3 = new javax.swing.JToggleButton();
        servico2 = new javax.swing.JToggleButton();
        servico1 = new javax.swing.JToggleButton();
        horario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verAgendamentoBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("GothicE", 0, 36)); // NOI18N
        jLabel1.setText("Marque o seu horário!");

        NomeUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NomeUsuario.setText(".");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Usuário Atual:");

        profissional1.setText("Thiago Pereira");

        profissional2.setText("João Pedro");

        profissional3.setText("Ana Júlia");

        profissional4.setText("Pedro Coelho");

        horario1.setText("13:00");

        horario3.setText("14:40");
        horario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horario3ActionPerformed(evt);
            }
        });

        horario2.setText("13:50");

        horario4.setText("15:30");

        horario5.setText("16:20");

        horario6.setText("17:10");

        horario7.setText("18:00");

        servico3.setText("Cabelo + Barba");

        servico2.setText("Barba");

        servico1.setText("Cabelo");

        horario.setText("Marcar Horario!");
        horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("R$20,00");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("R$30,00");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("R$40,00");

        verAgendamentoBtn.setText("Ver Agendamentos!");
        verAgendamentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAgendamentoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(92, Short.MAX_VALUE)
                                .addComponent(horario1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(horario2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(horario3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(horario4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(profissional1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(profissional2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(profissional3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(profissional4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(horario5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(horario6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(horario7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(verAgendamentoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(servico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(servico2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(servico3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addGap(163, 163, 163)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeUsuario)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profissional1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissional4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissional3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissional2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servico3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servico2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servico1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horario)
                    .addComponent(verAgendamentoBtn))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void horario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horario3ActionPerformed
        
    }//GEN-LAST:event_horario3ActionPerformed

    private void horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioActionPerformed
        
        Integer profEscolhido = null;
        String horaEscolhida = null;
        String servEscolhido = null;
        Date dataEscolhida;

        // PEGAR A DATA ESCOLHIDA ATRAVÉS DO CALENDÁRIO QUE IMPORTAMOS.
        dataEscolhida = jCalendar1.getDate();
        
        // ATRAVÉS DO TOGGLE BUTTON, FIZEMOS LAÇOS DE REPETIÇÃO PARA SE CASO ESSE BOTÃO TENHA SIDO PRESSIONADO, ELE SERÁ A OPÇÃO ESCOLHIDA DENTRE AS OUTRAS.
        if (profissional1.isSelected()) {
            profEscolhido = 23456;

        } else if (profissional2.isSelected()) {
            profEscolhido = 77010;

        } else if (profissional3.isSelected()) {
            profEscolhido = 84620;

        } else if (profissional4.isSelected()) {
            profEscolhido = 48629;
        }

        if (horario1.isSelected()) {
            horaEscolhida = "13:00";
        } else if (horario2.isSelected()) {
            horaEscolhida = "13:50";
        } else if (horario3.isSelected()) {
            horaEscolhida = "14:40";
        } else if (horario4.isSelected()) {
            horaEscolhida = "15:30";
        } else if (horario5.isSelected()) {
            horaEscolhida = "16:20";
        } else if (horario6.isSelected()) {
            horaEscolhida = "17:10";
        } else if (horario7.isSelected()) {
            horaEscolhida = "18:00";
        }

        if (servico1.isSelected()) {
            servEscolhido = "Cabelo";
        } else if (servico2.isSelected()) {
            servEscolhido = "Barba";
        } else if (servico3.isSelected()) {
            servEscolhido = "Cabelo + Barba";
        }

        CriarHorario novoHorario = new CriarHorario();

         //SALVANDO OS DADOS DO AGENDAMENTO NO BANCO DE DADOS CASO HAJA DISPONIBILIDADE.
        java.util.Date dataCalendario = dataEscolhida;

        java.sql.Date dataBanco = new java.sql.Date(dataCalendario.getTime());

        Horário agendamento = new Horário(dataBanco, horaEscolhida, servEscolhido, profEscolhido, clienteAtual);
        Horário disponibilidade = controller.disponibilidadeEmpregado(dataBanco, horaEscolhida, profEscolhido);
        
        if (disponibilidade == null) {
            agendamento.getCliente().getCpf();
            novoHorario.saveDataBanco(agendamento);
            
            //CAIXINHA COM AS INFORMAÇÕES DO AGENDAMENTO
            JOptionPane.showMessageDialog(this, "O horário foi marcado! \n"
                    + "Data: " + dataBanco
                    + "\nHora: " + horaEscolhida
                    + "\nServiço: " + servEscolhido
                    + "\nCliente: " + clienteAtual.getNome());
            // CASO O USUÁRIO TENHA SELECIONADO ALGUM HORÁRIO JÁ MARCADADO, ENTÃO O PROGRAMA IRÁ EXIBIR UMA MENSAGEM INFORMANDO ISSO.
        } else {
            JOptionPane.showMessageDialog(this, "Esse horário já está ocupado!");
        }
    }//GEN-LAST:event_horarioActionPerformed

    private void verAgendamentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAgendamentoBtnActionPerformed
        framepai.trocarPainel(new TabelaAgendamento(this.framepai, this.clienteAtual));
    }//GEN-LAST:event_verAgendamentoBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeUsuario;
    private javax.swing.JButton horario;
    private javax.swing.JToggleButton horario1;
    private javax.swing.JToggleButton horario2;
    private javax.swing.JToggleButton horario3;
    private javax.swing.JToggleButton horario4;
    private javax.swing.JToggleButton horario5;
    private javax.swing.JToggleButton horario6;
    private javax.swing.JToggleButton horario7;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton profissional1;
    private javax.swing.JToggleButton profissional2;
    private javax.swing.JToggleButton profissional3;
    private javax.swing.JToggleButton profissional4;
    private javax.swing.JToggleButton servico1;
    private javax.swing.JToggleButton servico2;
    private javax.swing.JToggleButton servico3;
    private javax.swing.JButton verAgendamentoBtn;
    // End of variables declaration//GEN-END:variables
}
